### ISSUE TITLE
Getting Warning Message when calling @ach_doc.to_s

### ISSUE THREAD

**Issue by kevinpiao0217** [jm81/ach#70]
Hi,

I'm getting `.rvm/gems/ruby-2.7.7@brokerage_engine-2_7_rails_5_2/gems/ach-0.4.11/lib/ach/field_identifiers.rb:54: warning: Using the last argument as keyword parameters is deprecated` warning messages when running `@ach_doc.to_s`. Please help and let me know if this is something I need to worry about. Thank you so much!

**Comment by henriquegasques** [comment]
Hi @kevinpiao0217,

You should only worry about that warning if/when you are planning to upgrade to Ruby 3:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Also, from the log message you provided, it looks like you're using ach version 0.4.11, which is pretty old (the latest version is 0.6.2).

Since I've only recently started using and helping maintain this gem, I don't know the details about what has changed in previous versions, so if you do upgrade, be careful and make sure to test as much as possible before going to production.

**Comment by henriquegasques** [comment]
Closing this since it appears to only affect old versions.
